### ISSUE TITLE
Symfony commands

### ISSUE THREAD

**Issue by crash21** [bamarni/symfony-console-autocomplete#11]
Hello,

For composer it works but how to make it work with symfony commands like cache:clear?
I do

php app/console ca[TAB] but nothing happens.

Any tips please?

Thanks

**Comment by bamarni** [comment]
hey there ;)

It should work if you remove `php` at the beginning.

**Comment by staabm** [comment]
@bamarni would it be a problem to also support commands with `php` in front?

**Comment by bamarni** [comment]
that would be nice indeed, the thing is that I'm not sure if / how it's possible, haven't tried it yet :-/

**Comment by crash21** [comment]
for me symfony commands are not working :(

**Comment by bamarni** [comment]
just try and you'll see :)

`app/console [TAB]`

**Comment by bamarni** [comment]
@staabm : I looked at this and don't think there is a clean solution, it'd require to create / change the php completion function to shift the first word in some cases and then continue with the symfony completion function.

I've added a note in the readme, it's preferable to rely on the shebang in that case, also shorter to type ^^

**Comment by staabm** [comment]
thx looking into it.
