### ISSUE TITLE
ZSH - fail silently if target tool can't be inspected

### ISSUE THREAD

**Issue by bamarni** [bamarni/symfony-console-autocomplete#14]
Currently for a non-symfony based tool : 

```
>  phpunit [TAB]
PHPUnit       -- 5.0.10 by Sebastian Bergmann and contributors.
unrecognized  -- option --no-ansi
```

This could also happen in a Symfony application if it's in a broken state (eg. fatal error during development). For those cases it should not try to autocomplete anything, there could be something similar to the bash completion check (https://github.com/bamarni/symfony-console-autocomplete/blob/master/templates/default.bash.tpl#L37).

**Comment by rquadling** [comment]
Happy to look at a pull request.

**Comment by rquadling** [comment]
No feedback or activity. Closing issue.
