### ISSUE TITLE
eval does not make autocomplete available

### ISSUE THREAD

**Issue by grasmash** [bamarni/symfony-console-autocomplete#20]
I've found that executing `eval "$(symfony-autocomplete)"` either on the terminal or adding it to `~/.bash_profile` does not make autocompletion available. 

However, running `symfony-autocomplete > $(brew --prefix)/etc/bash_completion.d/symfony-autocomplete` and re-sourcing `~/.bash_profile` does work.

This seems a bit heavy-handed. Any idea why the `eval` approach would fail?

**Comment by bamarni** [comment]
Strange indeed, not sure... What happens if you do this instead of eval : `symfony-autocomplete > tmp && source tmp`? And what is your bash version?

**Comment by sameg14** [comment]
I am running into the same issue here. I installed the package and created the entry in ~/.bash_profile but no dice. I am on a mac running OS X 10.12.2
<img width="584" alt="screen shot 2017-01-07 at 7 10 43 pm" src="https://cloud.githubusercontent.com/assets/76828/21746501/06ac3cc8-d50d-11e6-928c-a32ba57dc57c.png">

**Comment by bamarni** [comment]
@sameg14 : so you are also able to making it work by dumping it to `symfony-autocomplete > $(brew --prefix)/etc/bash_completion.d/symfony-autocomplete` but not with eval? If so I should probably add a note in the readme.

I used eval in the doc to have something that works for all setups but in that case it seems cleaner to do it as @grasmash.

**Comment by rquadling** [comment]
Solution is as documented.
