### ISSUE TITLE
alias of an alias?

### ISSUE THREAD

**Issue by admonkey** [bamarni/symfony-console-autocomplete#21]
Normally I would consider this an inconsiderate edge-case not worth complaining about, but considering the big deal that composer makes about running it with xdebug enabled, I thought someone might have a good idea for how to get this to work with aliases of aliases?

I have a custom php.ini that I load with composer:

```
alias c='php -c /home/jeff/php/composer.php.ini /usr/local/bin/composer'
```

So unfortunately, the `aliases` option doesn't fly in this situation:

```
symfony-autocomplete --aliases=c
```

Direct aliases work great:

```
alias comp='composer'
eval "$(symfony-autocomplete --aliases=comp)"
```

But then I end up with the foul performance warning:

> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

I need xdebug enabled in my default php cli because I rely on it with too many other tools.

**Comment by bamarni** [comment]
Completion scripts have this notion of words count, current word that need to get tracked. In your case the alias contains multiple words, so the script gets confused regarding those info I think :D Not that it's impossible, but I haven't implemented such thing unfortunately as it's a bit tricky.

A solution could be to put this in a one-liner shell script inside a directory from your $PATH and call it `composer`, I think that should work.

You might also be interested by [COMPOSER_DISABLE_XDEBUG_WARN](https://getcomposer.org/doc/03-cli.md#composer-disable-xdebug-warn).

**Comment by bamarni** [comment]
please let me know if that's still an issue and I'll reopen

**Comment by staabm** [comment]
Fyi, with composer 1.3 the xdebug warning should be gone in most cases as composer restarts the php process wit xdebug being disabled.
