### ISSUE TITLE
Support for fish

### ISSUE THREAD

**Issue by robdecker** [bamarni/symfony-console-autocomplete#23]
Any chance of getting support for http://fishshell.com/ ?

**Comment by bamarni** [comment]
That'd be a nice, I might take a look at it in the future but cannot guarantee when. If you'd like to contribute I'll gladly merge this out of course.

**Comment by bamarni** [comment]
@robdecker : I've made some refactoring first (#24) as with the current code it'd be hard to maintain more shells, I'll try to add fish support on top of this PR.

**Comment by bamarni** [comment]
@robdecker : For the moment I've only implemented static completion as I couldn't yet find how to autocomplete dynamic values with fish. It's in master at the moment so you can get it like this : 

    composer global require bamarni/symfony-console-autocomplete:dev-master
    # eg. completion for composer
    symfony-autocomplete composer > ~/.config/fish/completions/composer.fish

**Comment by TangMonk** [comment]
not work with symfony:
```
symfony-autocomplete symfony > ~/.config/fish/completions/symfony.fish


  [RuntimeException]

    Incorrect usage: flag provided but not defined: -format



dump [--script-options SCRIPT-OPTIONS] [--aliases ALIASES] [--disable-default-tools] [--shell SHELL] [--] [<script>]
```
