### ISSUE TITLE
Start path completion from certain directory

### ISSUE THREAD

**Issue by dzoeteman** [bamarni/symfony-console-autocomplete#27]
I'd like to be able to set the shell path completion from a certain directory. Is this already possible, or can this be implemented?

Example:

current working dir: /var/www/someapp
complete from: /var/www/someapp/somedir
so that you can have completion for example on file /var/www/someapp/somedir/somefile.php

**Comment by bamarni** [comment]
Why not putting them in your $PATH? If you don't want to do it globally you can use a tool like https://direnv.net/, so that the $PATH is only set when you are inside that directory.

**Comment by gdscei** [comment]
@bamarni I'd like to use this feature for a tool useful for more people than just me, so just wondering if it's possible to implement this without adding to $PATH.

**Comment by bamarni** [comment]
Are you looking for static completion or "on-the-fly" completion? For the latest one, I think it should work already with `symfony-autocomplete --aliases=somefile.php`.

**Comment by rquadling** [comment]
Is this still an issue?

**Comment by rquadling** [comment]
Closing. No feedback.
