### ISSUE TITLE
Feature request: make the script able to read from stdin

### ISSUE THREAD

**Issue by Fuco1** [bamarni/symfony-console-autocomplete#28]
We run our software in docker and I think that might be interfering with the way symfony process starts the script to get the raw list of commands.  I can dump the list no problem with `docker-compose exec`, so it would be cool if I could just dump it into symfony-autocomplete and get the tab-complete script back out (as I do now, on stdout, which is awesome!)

The usage would be something like

    my-non-obvious-way-to-execute-the-script | symfony-autocomplete.

Would you be interested in this?  I might try to provide a PR, it shouldn't be difficult, just a test with `istty`.

**Comment by bamarni** [comment]
By `my-non-obvious-way-to-execute-the-script` do you mean something like `composer list --raw` for example? This is how the tool works internally, I don't think it's a clean solution to expose it and allow it as input directly.

If `symfony-autocomplete` is running from the same container as the tool(s) you're dumping the completion for, it should work properly, what problem do you face exactly with docker?

**Comment by Fuco1** [comment]
I'm not running the dumper inside the docker, we have helper scripts which "tunnel" into the docker, run the stuff there and return the values out as normal text (to stdout).

I can pass `list --raw` to our helper and it returns the data correctly but `symfony-autocomplete` can't do that for some reason.  I don't know how the process is started internally but it breaks somewhere along the way.

**Comment by bamarni** [comment]
I'd appreciate if you could debug it further so we can fix the root cause directly, the command is triggered here https://github.com/bamarni/symfony-console-autocomplete/blob/656b6b675861fcc38818a559328e3e9895ea2711/src/DumpCommand.php#L75

Maybe you don't have awk in the container? Or it is based on busybox / alpine and not gnu compatible? Maybe switching to php for parsing the output would be safer.

**Comment by Fuco1** [comment]
After I removed the `awk` pipe I get the following error:

```
  [RuntimeException]
  Traceback (most recent call last):
    File "bin/docker-compose", line 3, in <module>
    File "compose/cli/main.py", line 64, in main
    File "compose/cli/main.py", line 116, in perform_command
    File "compose/cli/main.py", line 462, in exec_command
    File "site-packages/dockerpty/pty.py", line 338, in start
    File "site-packages/dockerpty/io.py", line 32, in set_blocking
  ValueError: file descriptor cannot be a negative integer (-1)
  Failed to execute script docker-compose
```

Our script executes `exec docker-compose exec app "$0" "$@"` to run the command.  The image is based on Debian 8.

I can `exec bash` into the container and do it there though... I've noticed the `--shell` option :) (we run bash inside for obvious reasons).  So that's fine by me.  I guess this is a bit unusual case so it's up to you if you want to proceed further or close.

**Comment by bamarni** [comment]
So did you resolve it with the `--shell` option? My bad but I didn't got your problem exactly.

In any case feel free to close if it's fixed :)

**Comment by Fuco1** [comment]
No, I assumed you dump for the current shell, but I can dump fish completions from bash, so I did that from inside the container... with some volume mapping magic I got it out so there's that.

OK, I'll close, but it would probably be a good idea to remove all extra dependencies to make this more portable.
