### ISSUE TITLE
support symfony3? 

### ISSUE THREAD

**Issue by videni** [bamarni/symfony-console-autocomplete#29]

**Comment by bamarni** [comment]
Doesn't it work on symfony 3?

**Comment by videni** [comment]
@bamarni,  I think it not , symfony3 directory structure changed,  the dedicated `bin` is for executable script now.

**Comment by rquadling** [comment]
The restriction on Symfony 3 and 4 was removed recently. Is this still an issue?

**Comment by rquadling** [comment]
Closing.  No feedback.

**Comment by ryancastle** [comment]
The current version doesn't seem to support Symfony 3+
