### ISSUE TITLE
Usage with docker

### ISSUE THREAD

**Issue by flohw** [bamarni/symfony-console-autocomplete#32]
I want to use this tool inside a php docker container.
I get the error "Notice: Undefined index SHELL in bamarni/symfony-console-autocomplete/symfony-autocomplete on line 68"

Is it possible to run or update the scripts to be able to run inside a docker container ?

Thanks.

**Comment by rquadling** [comment]
Strangely enough I've just seen the same issue.
`docker exec -it php bash` gives me a shell prompt inside my PHP-FPM container.
Running `set | grep SHELL` and I see `SHELL=/bin/bash`.
Running `php -i  | grep SHELL` and I get nothing. My `variables_order` doesn't include `E`, so no environment variables added, but even `php -d variables_order=EPGCS -i | grep SHELL` yields no joy.

I think, if you want to run this, you'll need to provide the shell value manually using the `--shell` option (see https://github.com/bamarni/symfony-console-autocomplete/blob/master/src/DumpCommand.php#L23).

**Comment by rquadling** [comment]
`php -d variables_order=GPCSE -r 'print_r($_ENV);` shows the environment variables that are being presented to PHP in the docker container. No SHELL. No OS.

**Comment by rquadling** [comment]
Based upon https://github.com/moby/moby/issues/33794, the only solution I can find at the moment is to supply the SHELL env to the `docker exec` command.

`docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -e SHELL=bash -it php bash`

Running symfony-autocomplete in the container now generates the completion code without the error.

**Comment by rquadling** [comment]
Updated README with notes regarding the lack of the `SHELL` environment variable when using `docker exec` to connect to a container.
