### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by JRCrawford** [bamarni/symfony-console-autocomplete#38]
Ran the following as per instructions on readme:
```
composer global require bamarni/symfony-console-autocomplete
symfony-autocomplete composer
symfony-autocomplete composer > $(brew --prefix)/etc/bash_completion.d/composer
```

Which then gave the error:
**zsh: command not found: symfony-autocomplete**

**Comment by rquadling** [comment]
Do you have the composer global bin in your path?

My path includes `$HOME/.composer/vendor/bin:./vendor/bin:./node_modules/.bin`.

This allows me to run global composer bins, local vendor bins, and local node bins.

**Comment by rquadling** [comment]
symfony-autocomplete is installed in the global composer binaries folder.
That's in `$HOME/.composer/vendor/bin`. Take a look. If you see it there, then the path is missing. This is separate to the location of composer itself.

Running `which composer` will tell you where that is installed.

**Comment by rquadling** [comment]
Did you get this sorted?

**Comment by JRCrawford** [comment]
No I didn't.  I added this folder (~/.composer/vendor/bin) to my path however I now get a bunch of code outputted whenever I try and run symfony-autocomplete.  See here: https://imgur.com/a/BG3cB for details.

**Comment by rquadling** [comment]
Excellent! Now go and reread https://github.com/bamarni/symfony-console-autocomplete#static-setup. You need to capture the output and send it to the appropriate place.

**Comment by rquadling** [comment]
All done?

**Comment by JRCrawford** [comment]
I wasn't able to get it working.  However I did find out about the composer and symfony2 plugin for zsh.  These do exactly what I need them to do as seen here: https://i.imgur.com/AevTy5I.png

Marking this as closed.
