### ISSUE TITLE
composer autocompletes, console only globs

### ISSUE THREAD

**Issue by torenware** [bamarni/symfony-console-autocomplete#40]
Counter to #11, I'm not getting bin/console to work at all with symfony-console-autocomplete.

On Ubuntu 18.08, I've done the following:

- composer global require bamarni/symfony-console-autocomplete

- adding `eval $(symfony-autocomplete)` in ~/.bashrc causes a syntax error.

- `symfony-autocomplete composer | sudo tee /etc/bash_completion.d/composer` almost works; turns out that since /usr/share/bash_autocomplete/ is installed, it's the only one that's recognized by complete.

- `symfony-autocomplete composer | sudo tee /usr/share/bash-completion/completions/composer` is actually read and used.

At this point, on starting up a shell, composer autocompletes.  But bin/console (from a Symfony project directory) only "globs"; the autocompletion stuff does not get invoked at all.

I'm not sure what diagnostics you need, but running `complete -p`....

```
vagrant@homestead:/usr/share/bash-completion/completions$ complete -p composer
complete -o default -F _composer composer
vagrant@homestead:/usr/share/bash-completion/completions$ complete -p console
-bash: complete: console: no completion specification
vagrant@homestead:/usr/share/bash-completion/completions$ complete -p bin/console
complete -F _minimal bin/console

```
What more do I have to do in order to get this to work?

**Comment by rquadling** [comment]
Hi. I'm not on Ubuntu and I'm not 100% sure what bin/console is. I assume it is some sort of Symfony Console command runner?

Is it just the case that you need to run symfony-autocomplete for bin/console?

I'm on OSX. I use composer and have a run script in that to update all my auto-completions.

(snipped example).
```
  "scripts": {
    "update-autocomplete": "scripts/update-autocomplete.sh"
  }
```

That script ...

```
#!/usr/bin/env bash

echo Building bash auto-completion for artisan
./vendor/bin/symfony-autocomplete ./artisan > $(brew --prefix)/etc/bash_completion.d/artisan

echo Building bash auto-completion for composer
./vendor/bin/symfony-autocomplete composer > $(brew --prefix)/etc/bash_completion.d/composer

echo Building bash auto-completion for phinx
./vendor/bin/symfony-autocomplete ./vendor/robmorgan/phinx/bin/phinx > $(brew --prefix)/etc/bash_completion.d/phinx

echo Building bash auto-completion for wu
./vendor/bin/symfony-autocomplete ./wu > $(brew --prefix)/etc/bash_completion.d/wu

echo Removing bash auto-completion for pipeline as no longer used
rm -rf $(brew --prefix)/etc/bash_completion.d/pipeline

echo Recycle your terminal to load the auto-completions.
```

Does this help?

Internally, the symfony-autocomplete is attempting to run the command you've supplied with the options `list --format=xml` and then parse/process the results.

If `bin/console list --format=xml` produces a valid XML file, then symfony-autocomplete should be able to do its thing.

In my script, I'm creating a separate auto completer for each of my commands (and dropping one I no longer need).

This whole process takes around 10s to run as it builds and process all the XML files.

**Comment by rquadling** [comment]
No feedback
