### ISSUE TITLE
symfony-autocomplete: command not found

### ISSUE THREAD

**Issue by lambasoft** [bamarni/symfony-console-autocomplete#41]
Hey,
After installing globally using:
`composer global require bamarni/symfony-console-autocomplete`

I keep getting the following error, even after restarting my terminal:
`symfony-autocomplete: command not found`

Any advice?

**Comment by rquadling** [comment]
Do you have `~/.composer/vendor/bin` in your path?

I'm on MacOS and my path includes ...

`/Users/richardquadling/.composer/vendor/bin:./vendor/bin:./node_modules/.bin`

So, for my global and local composer installations and my local npm managed installations, any "binaries" installed are accessible without needing to always put the path in.

**Comment by rquadling** [comment]
No feedback.

**Comment by zhil** [comment]
for Ubuntu 19 you just need to add in ~/.bashrc
```
PATH="$HOME/.config/composer/vendor/bin:$PATH"
eval "$(symfony-autocomplete)"
```

**Comment by tofra** [comment]
@rquadling This should really be in the README :-)

**Comment by ktomk** [comment]
Well, in the README/docs is fine, but the question would be which one and how far. **Composer** has this specifically documented:

From `composer(1)` [**global** command](https://getcomposer.org/doc/03-cli.md#global), using the `friendsofphp/php-cs-fixer` package as an example:

> This can be used to install CLI utilities globally. Here is an example:
>
> ~~~
> php composer.phar global require friendsofphp/php-cs-fixer
> ~~~
>
> Now the php-cs-fixer binary is available globally. Make sure your global vendor binaries directory is in your $PATH environment variable, you can get its location with the following command :
>
> ~~~
> php composer.phar global config bin-dir --absolute
> ~~~

As users can configure their userspace as they wish (compare [_Vendor binaries_](https://getcomposer.org/doc/articles/vendor-binaries.md) etc.) I'd suggest to refer to the canonical resources/documentation.

**Comment by rquadling** [comment]
I was just about to comment ... and then @ktomk said it much better.

This utility relies on Composer being setup to work correctly for you. We don't know how you work.

**Comment by tofra** [comment]
I just commented it because I needed to search for 10 minutes to get this package working. Something like 'If you get command not found, make sure you added ... to path...' is enough. Just some quick hints. (or at the bottom: troubleshooting tips)
Because it is nowhere mentioned at https://getcomposer.org/download/ that it should be required (or a good idea to do)

**Comment by ktomk** [comment]
Yes, there is a learning curve and for some its only 10 minutes, for me it is often longer. In any case it is now documented with this project in this issue public on the internet. An internet search should reveal it in the future and we have the composer documentation now properly referenced here, both in form of a hypertext reference and excerpt (quote).

So at least we can see an improvement even it does not yet cover all the cases. E.g. when adding to PATH does not suffice or is not well understood by the user.

A more canonical command could be:

~~~
eval "$("$(composer global config bin-dir --absolute)"/symfony-autocomplete)"
~~~

with the pre-condition that `composer` is within PATH, which is likely the case when `composer global install ...` worked earlier.
