### ISSUE TITLE
Usage in cygwin + win32 PHP: cannot find non standard script

### ISSUE THREAD

**Issue by MatteoOreficeIT** [bamarni/symfony-console-autocomplete#43]
We've got a problem using `symfony-autocomplete` in cygwin  , the problem was Symfony Process cannot find and run in path our Symfony based script because under windows Symfony Process can only run `.exe` or `.bat`  ( also bypass_shell = true ) which cannot run shebanged bash-style scripts ( we are not in a bash env ) and many custom script base con Symfony command are not executable in windows, they need to be run with their right interpreter

Composer is usually deployed on windows like a `composer.bat` which can be found in path and ran, a workaround could be supply a `symfony-autocomplete` cli option to run script like a php script

`new Process(['php','<script>'],...`

**Comment by rquadling** [comment]
Are you running the cygwin version of PHP or win32 version? Running win32 in cygwin is STILL a win32 app. You'll need the cygwin version of PHP (is there such a thing? I recall there was, but can't be sure).

**Comment by MatteoOreficeIT** [comment]
Hi, I am running an hybrid conf, running many version of php for win32 or cygwin under W10 but always via mintty terminal, we usually switch them via a bash script sourcing, furthermore a script handles pathname conversion on invocations between Win32 or cygwin php versions which differently understand back or forward slash pathname.

The big problem was symfony-console-autocomplete cannot see as a script the Laravel `artisan` script

```bash
$ symfony-autocomplete --disable-default-tools artisan

In DumpCommand.php line 79:

  "artisan" non è riconosciuto come comando interno o esterno,
   un programma eseguibile o un file batch.

dump [--script-options SCRIPT-OPTIONS] [--aliases ALIASES] [--disable-default-tools] [--shell SHELL] [--] [<script>]
```

As you can see in https://github.com/laravel/laravel the artisan command is going to be shipped without a .bat version, and a lot of other examples could be found where a .bet counterpart is not available. 

Under cmd terminal you need to run `php artisan` command because .bat is not available, so my suggestion was to provide a command line switch to pointo to a php CLI software could be invoked in shell like `php mycommand` instead of `mycommand`

**Comment by rquadling** [comment]
Does the following work for you?

```
$ symfony-autocomplete --disable-default-tools "php artisan"
```

**Comment by MatteoOreficeIT** [comment]
Thanks @rquadling , it works ! 

This could be shipped in a doc update also

Thanks

**Comment by rquadling** [comment]
Done. https://github.com/bamarni/symfony-console-autocomplete/commit/bcd5a907e9e7bd25f7ad63eaaee3c97560f0c71f
