### ISSUE TITLE
How to use it for an alias of Composer?

### ISSUE THREAD

**Issue by hkdobrev** [bamarni/symfony-console-autocomplete#5]
I have successfully set this wonderful library up and it works for completions of `composer`. However I use `c` as an alias to `composer`. And it doesn't work for the alias which is normal.

However I have `g` aliased to `git` and the completion for `g` works by using:

```
complete -o default -o nospace -F _git g
```

https://github.com/hkdobrev/dotfiles/blob/b923c4128ba25197cce0afb085447e95b2aab4a1/.aliases#L34-L35

I've tried setting it up with:

```
complete -o default -o nospace -F _symfony c
```

But it doesn't work. Any suggestions on how to set this up?

**Comment by bamarni** [comment]
You could also generate this line automatically with the "--aliases" option :  `symfony-autocomplete --aliases="c"`.

I just checked and indeed, somehow aliases only work with zsh at the moment. Git completion script is probably doing something special to allow aliases, I'll try to dig into this :+1:

**Comment by bamarni** [comment]
Apparently it is a limitation (http://blog.openendings.net/2015/06/bash-completion-of-aliased-commands.html), git is using something similar : https://github.com/git/git/blob/master/contrib/completion/git-completion.bash#L2721-L2737

I'll try to adapt the script.

**Comment by bamarni** [comment]
My bad, it was something else. It should work whenever you'll update the package.

**Comment by ktomk** [comment]
I just tried with from current master and adding two `--aliases` didn't work for static file creation (default: bash). I could handle it with a little sed script appending to the last line of the script, that did work. But perhaps I'm missing something what the aliases should do.

**Comment by bamarni** [comment]
@ktomk : My previous fix was indeed only for the dynamic script, I just pushed something to master for the other one 15b58be460eb925bf9a1916569c8dda4f9ddebf5, should work now :)

**Comment by ktomk** [comment]
@bamarni: Thanks, I just tried against the latest master. I can see the new comments in the bash file and I could get `--aliases`  working. It creates one additional line for each alias. Thanks!
