### ISSUE TITLE
Doesn't work for the "symfony" cli tool

### ISSUE THREAD

**Issue by RikudouSage** [bamarni/symfony-console-autocomplete#52]
I get the error:

`Incorrect usage: flag provided but not defined: -format`

Which I guess means that the command removed the --format option.

**Comment by rquadling** [comment]
Can you let me know what version of PHP, Symfony Console, and the autocompleter you are using please?

**Comment by rquadling** [comment]
Closing due to no feedback.

Please re-open this issue if you have more information regarding this issue.

**Comment by sarim** [comment]
Thats because `symfony` command doesn't support `list --format=xml`. It only has the basic `list`.

**Comment by msinghnanhre** [comment]
Trying to set up symfony project with, --cloud --webapp and --docker but getting this error Incorrect usage: flag provided but not defined: -docker
