### ISSUE TITLE
Problem "bash: _get_comp_words_by_ref: command not found" on docker php:7.4-fpm

### ISSUE THREAD

**Issue by HarasimowiczKamil** [bamarni/symfony-console-autocomplete#55]
Dockerfile
```
FROM php:7.4-fpm

RUN apt-get update && apt-get install -y \
    openssl \
    git \
    unzip \
    wget \
    bash-completion

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
&& composer --version

# autocompleter
RUN composer global require bamarni/symfony-console-autocomplete \
&& echo 'export PATH="$PATH:~/.composer/vendor/bin/"' >> ~/.bashrc \
&& echo 'eval "$(symfony-autocomplete)"' >> ~/.bashrc

WORKDIR /var/www
```

bash_completion version:

```
# apt-cache policy bash-completion
bash-completion:
  Installed: 1:2.8-6
  Candidate: 1:2.8-6
  Version table:
 *** 1:2.8-6 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

When try to use:

```
# composer bash: _get_comp_words_by_ref: command not found
html/bash: _get_comp_words_by_ref: command not found
bash: _get_comp_words_by_ref: command not found
bash: _get_comp_words_by_ref: command not found
```

Am i doing something wrong?

**Comment by rquadling** [comment]
It looks like bash-completion is not installed. That is the script that has the bash function that you are missing.

In my MacOS `.bash_profile`, my HomeBrew installed bash-completion added ..

```
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

I suspect you'll need to have something similar in your `.bashrc` (if that is the right file ... I'm never sure which one should be used).

**Comment by HarasimowiczKamil** [comment]
@rquadling bash_completion is installed in first RUN. I want use it on docker

**Comment by rquadling** [comment]
Installing bash_completion only places the necessary code onto the drive. It does not write the necessary command to `~/.bashrc` which is why things are failing.

If you shell into your image, and run `set | grep 'BASH_COMPLETION[_=]'`, what do you get?

On my MacOS host, I get ...

```
BASH_COMPLETION=/usr/local/etc/bash_completion
BASH_COMPLETION_COMPAT_DIR=/usr/local/etc/bash_completion.d
BASH_COMPLETION_DIR=/usr/local/etc/bash_completion.d
```

These envvars are set by the execution of the `/etc/bash_completion` on MacOS. I think this command (or something similar for non MacOS) is missing for the shell you are running.

**Comment by flaushi** [comment]
yup, you need another line like 
```
RUN echo "source /etc/profile.d/bash_completion.sh" > ~/.bashrc
```
