### ISSUE TITLE
Compatibility with Symfony local server

### ISSUE THREAD

**Issue by ro0NL** [bamarni/symfony-console-autocomplete#59]
AFIAK the local server itself is also SF console application, but it doesnt autocomplete:

```
symfony <TAB><TAB>
````

![image](https://user-images.githubusercontent.com/1047696/93991398-882b2880-fd8c-11ea-91d1-ceb59ca866e5.png)

another interesting case is autocompleting `symfony console` individually, which just wraps `bin/console` :)

**Comment by TomaszGasior** [comment]
`symfony` proprietary binary is not written in PHP and it does not use Symfony Console library for which the symfony-console-autocomplete project exists.

**Comment by ro0NL** [comment]
> it does not use Symfony Console library

sure looks like it :sweat_smile:  but i believe you're right yes. It's something else.

Closing as such, binary is a black box. Either works or doesnt regarding this lib.
