### ISSUE TITLE
Ubuntu12 lts: symfony-autocomplete command not found

### ISSUE THREAD

**Issue by staabm** [bamarni/symfony-console-autocomplete#7]
after installing this tool via 
`sudo composer global require bamarni/symfony-console-autocomplete`
I get a "command not found error" after invoking `symfony-autocomplete` on the bash.

I did a ssh relogin after installation completed successfully.

```
$ php -v
PHP 5.5.30-1+deb.sury.org~precise+1 (cli) (built: Oct  4 2015 16:14:34)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with blackfire v1.8.0, https://blackfire.io, by Blackfireio Inc.
```

`composer` is updated to the latest version as of today.

any hints?

**Comment by staabm** [comment]
ok, just realised that I had not properly setup my global composer project in my dev box.

**Comment by staabm** [comment]
fixed by https://github.com/bamarni/symfony-console-autocomplete/pull/8

**Comment by bamarni** [comment]
:+1:
