### ISSUE TITLE
Not working with Symfony 6.

### ISSUE THREAD

**Issue by jfcherng** [bamarni/symfony-console-autocomplete#70]
> PHP Fatal error:  Declaration of Application::getDefinition() must be compatible with Symfony\Component\Console\Application::getDefinition(): Symfony\Component\Console\Input\InputDefinition in /root/.composer/vendor/bamarni/symfony-console-autocomplete/bin/symfony-autocomplete on line 39

> PHP Fatal error:  Declaration of Application::getCommandName(Symfony\Component\Console\Input\InputInterface $input) must be compatible with Symfony\Component\Console\Application::getCommandName(Symfony\Component\Console\Input\InputInterface $input): ?string in /root/.composer/vendor/bamarni/symfony-console-autocomplete/bin/symfony-autocomplete on line 27

> PHP Fatal error:  Declaration of Application::getDefaultCommands() must be compatible with Symfony\Component\Console\Application::getDefaultCommands(): array in /root/.composer/vendor/bamarni/symfony-console-autocomplete/bin/symfony-autocomplete on line 32

Symfony 6 adds quite lots of type hinting which changes function signatures, so [this](https://github.com/bamarni/symfony-console-autocomplete/commit/5c4bb625e24254afad08d306f37d47b3bc58abea) won't magically make it support Symfony 6.

**Comment by ktomk** [comment]
oh snap, thanks for raising this.

I'm a bit puzzled by this one, it looks like that in the projects' `composer.json`, even if `composer ... --no-dev` is in use,

~~~
    "require-dev": {
        "symfony/console": "2.8.*"
    },
~~~

blocks raising this. which makes me wonder why this is only about symfony/console v6 and not earlier.

I have to build back for now and consider this for a moment.

Most straight forward is perhaps to add it with 1.5.x and drop php 7.0 support with it.

**Comment by ktomk** [comment]
Released in v1.5.3, v1,4,x us not supported.

**Comment by ktomk** [comment]
@jfcherng: Do you remember the PHP version you've been using with that component? Just asking b/c I think this fix here - while working - removed too much necessary and we could do better (e.g. conditional installs). As we're currently improving the build some more information would help me to reproduce this and better understand similar issues:

- PHP version
- The requirement that triggered this (if you can pin-point it, I'd guess it is the `symfony/console` package, version 6-ish?)

**Comment by jfcherng** [comment]
> * PHP version

Most likely `8.0` I would guess.

> * The requirement that triggered this 

Iirc, the error is triggered when trying to make a shell completion (not necessary for Symfony things, but just any shell completion since `bamarni/symfony-console-autocomplete` will be executed when doing a completion?).

> (if you can pin-point it, I'd guess it is the `symfony/console` package, version 6-ish?)

I think yes, from the error msg.
