### ISSUE TITLE
PHP 8.1 deprecated return type

### ISSUE THREAD

**Issue by sviluppo** [bamarni/symfony-console-autocomplete#72]
Hello, i am getting this error with PHP 8.1 it could be possible that a new version of `symfony/console` is needed?
At least to what i understood from here: https://github.com/symfony/symfony/pull/42260

`bash: /etc/bash_completion.d/composer: line 2: syntax error near unexpected token `('
bash: /etc/bash_completion.d/composer: line 2: `Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /tmp/symfony-console-autocomplete-master/vendor/symfony/console/Helper/HelperSet.php on line 112'`

Thank you!

**Comment by ktomk** [comment]
Thanks for the report, it looks like PHP errors are put into the bash template, and those PHP errors are 8.1 deprecation warnings which should be able to circumvent with  `#[\ReturnTypeWillChange] attribute` (which is backwards compatible as a standard PHP comment).

However the notice needs to be suppressed for `/vendor/symfony/console/Helper/HelperSet.php`.

Perhaps PHPs' `@` error suppression operation can do it.

How are you generating `/etc/bash_completion.d/composer`? Explicit or by use? Can you share your usage pattern so that it's clear what to do to reproduce (with PHP 8.1).

**Comment by sviluppo** [comment]
Hi @ktomk, i'm using it in my Dockerfile.

```
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && curl -sSL "https://github.com/bamarni/symfony-console-autocomplete/archive/master.zip" > /tmp/symfony-console-autocomplete.zip \
    && unzip -d /tmp /tmp/symfony-console-autocomplete.zip \
    && composer --working-dir=/tmp/symfony-console-autocomplete-master install \
    && mkdir /etc/bash_completion.d \
    && /tmp/symfony-console-autocomplete-master/bin/symfony-autocomplete --shell=bash --aliases=codecept > /etc/bash_completion.d/composer \
    && rm -fr /tmp/symfony-console-autocomplete* /root/.composer
```

And i call it through a Makefile with the command `docker exec -it container-php bash`.

When i launch this command i get into the bash but with the error.

**Comment by sviluppo** [comment]
@ktomk any news? 

Thank you!

**Comment by ktomk** [comment]
Yes, but the description was incomplete to fully reproduce ad-hoc:

When you execute symfony-autocomplete take care that the PHP CLI interpreter is displaying errors on standard error.

And not on standard output as then the generation of the autocompletion file then is intermixed with PHP error messages.

Compare:

~~~
RUN printf 'display_errors = STDERR\n' > /usr/local/etc/php/php.ini
~~~

https://github.com/ktomk/symfony-console-autocomplete/blob/7b2ea47ed7cb3e9f071e1cd9d11ded4f794abaf0/issue-72/Dockerfile#L5

Please let me know if this solved your issue.

**Comment by sviluppo** [comment]
Thank you @ktomk the solution worked!

Sorry if the description was incomplete.

I changed it: `RUN printf 'display_errors = STDERR\n' > ${PHP_INI_DIR}/conf.d/99-overrides.ini`

**Comment by ktomk** [comment]
@sviluppo Thanks for confirmation. Seems to be useful to make this setting explicit in the utility itself as these messages should never go to standard output for the utility. Available in [v1.5.4] which just got out, details in 5adeafbc238e896b780eb8353e82cf7d6539e781 .

So this modification should not be necessary any longer according to my tests for a better out-of-the-box experience.

If you could confirm this fix release would be great, my tests looked fine so far.

[v1.5.4]: https://github.com/bamarni/symfony-console-autocomplete/releases/tag/v1.5.4

**Comment by sviluppo** [comment]
@ktomk :muscle: 

Tested with php:8.1-fpm

If i set on my override php.ini file `display_errors = On` the problem still occurs but if i comment it completely the error disappear.

If i set on my override php.ini file `display_errors = On` and i move my copying of the override php.ini file **After** the symfony-console-autocomplete the error disappear.

Maybe must be added into the Readme that the order matter?

**Comment by ktomk** [comment]
Well the order should not matter - at least not for functionality.

On the CLI the error should always go to standard error.

That means with docker build it should be displayed on standard error. Perhaps that is what you describe?

From what I can see here locally (all in updated [issue-72 directory over there](https://github.com/ktomk/symfony-console-autocomplete/tree/issue-72/issue-72)) this should be fine, but just in case I'm wrong point me to it.

For users that had previously `display_errors = Off`, they can now see the diagnostic messages on standard error as well. Me thinks this is useful for maintenance. @sviluppo

**Comment by sviluppo** [comment]
Colors are available but they are not shown in red.
#https://github.com/ktomk/symfony-console-autocomplete/tree/issue-72/issue-72 works like a charm, yesterday i tested also with php:8.1-fpm using apt.

Maybe there is another thing in my override php.ini that affect it `display_startup_errors = On` if i turn this off or i set it to STDERR (that probably set it off because this directive is bool) the error disappear again.

 I think that this modification cover most of the cases, if you want to investigate more i can pass you my dockerfile and php.ini.

**Comment by ktomk** [comment]
> I think that this modification cover most of the cases, if you want to investigate more i can pass you my dockerfile and php.ini.

That would be good b/c right now I get the impression not seeing something.

**Comment by ktomk** [comment]
Okay, that sounds like it should be. Thank you for double checking.

This issue is being closed with the best of intentions as we have gained the understanding that the latest version will prevent the reported issue from occurring. If in the future this turns out to be untrue, we are left with the hope that it was just meant to be and should not prevent this issue from being reopened.

Thank you @sviluppo
