### ISSUE TITLE
Static setup for zsh

### ISSUE THREAD

**Issue by stof** [bamarni/symfony-console-autocomplete#9]
Does the static setup work for ZSH or is it bash-only ? Looking at the code, it looks like it is not yet implemented, but the readme does not explain it.

**Comment by bamarni** [comment]
It is indeed bash only for the moment, I'll try to improve zsh static script first (complete global options, complete options only if current word starts by "--" otherwise fallback to default filesystem completion), then I'll adapt it to static :+1:

**Comment by bamarni** [comment]
It should now be supported with the latest version.
